name:                envoy
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/envoy#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2021 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - proto-lens-runtime
  - proto-lens-protobuf-types

library:
  source-dirs: generated
